language: java

jdk:
   - oraclejdk8

sudo: required

services:
  - docker

install: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/jvm

script:
  - mvn clean install

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=alexey777/notes-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY SERVICE
  - export REGISTRY=alexey777/notes-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # NOTES SERVICE
  - export NOTES_SERVICE=alexey777/notes-service
  - docker build -t $NOTES_SERVICE:$COMMIT ./notes-service
  - docker tag NOTES_SERVICE:$COMMIT NOTES_SERVICE:$TAG
  - docker push NOTES_SERVICE

  # GATEWAY SERVICE
  - export GATEWAY=alexey777/notes-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

notifications:
    email:
      recipients:
        - alexeyzhytnik@gmail.com
      on_success: never
      on_failure: always