language: java

jdk:
   - oraclejdk8

sudo: false

install: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/jvm

script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      recipients:
        - alexeyzhytnik@gmail.com
      on_success: never
      on_failure: always