version: '2'
services:
  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  notes-service:
    build: notes-service
    ports:
      - 8000:8000